name: Android Testing
on: push

jobs:
  run-tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Update secrets local.properties
        run: echo "$LOCAL_PROPERTIES" > /home/runner/work/tempus/tempus/local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Update secrets google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" > /home/runner/work/tempus/tempus/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Run connected tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
            api-level: 30
            target: google_apis
            arch: x86_64
            script: ./gradlew connectedCheck