name: Android Testing
on: push

jobs:
  android-tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      - name: Update secrets local.properties
        run: echo "$LOCAL_PROPERTIES" > $GITHUB_WORKSPACE/local.properties
        env:
          LOCAL_PROPERTIES: ${{ secrets.LOCAL_PROPERTIES }}

      - name: Update secrets google-services.json
        run: echo "$GOOGLE_SERVICES_JSON" > $GITHUB_WORKSPACE/app/google-services.json
        env:
          GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES_JSON }}

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Create AVD and launch emulator
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86
          profile: Nexus 6
          script: ./gradlew connectedCheck
          disable-animations: true

      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest
